# Generated by Django 4.2.1 on 2024-05-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_productos_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
